name: Compile LaTeX and upload PDF

on:
  push:
    branches:
      - main  # o el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex  # Reemplaza 'main.tex' con el nombre de tu archivo principal .tex

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: main.pdf  # Reemplaza 'main.pdf' con el nombre de tu archivo PDF compilado